const notes = [
  {
    descriptionA: [
      {
        _key: 'fda2a4586e1c',
        _type: 'block',
        children: [
          {
            _key: '9959f034edbc0',
            _type: 'span',
            marks: ['em'],
            text: 'A lion that owns a castle.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionB: [
      {
        _key: '51a3454ee3e3',
        _type: 'block',
        children: [
          {
            _key: 'f070352f558b',
            _type: 'span',
            marks: ['em'],
            text: 'A “king” who enjoys watching things and knowing what time it is.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '949b0de6865f',
        _type: 'block',
        children: [
          {
            _key: 'e9432c63a144',
            _type: 'span',
            marks: [],
            text: 'Stargazing last night',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'cf4a24149b06',
        _type: 'block',
        children: [
          {
            _key: '3a8c43961a2a',
            _type: 'span',
            marks: [],
            text: 'Claims',
          },
          {
            _key: 'ac531549ad29',
            _type: 'span',
            marks: ['strong'],
            text: ' ',
          },
          {
            _key: 'f532a96506a4',
            _type: 'span',
            marks: ['em'],
            text: 'Ñenn ',
          },
          {
            _key: '381f8d889071',
            _type: 'span',
            marks: [],
            text: 'didn’t move last night.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '5e7209ea0aa8',
        _type: 'block',
        children: [
          {
            _key: '7682645efb3d',
            _type: 'span',
            marks: [],
            text: 'Saw',
          },
          {
            _key: 'd06f0e37fb00',
            _type: 'span',
            marks: ['em'],
            text: ' Lucky',
          },
          {
            _key: '6d9ba173dc9f',
            _type: 'span',
            marks: [],
            text: ' leave his house at ',
          },
          {
            _key: '3ab63fa9f0e8',
            _type: 'span',
            marks: ['em'],
            text: '9:52PM',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '83ea213676d7',
        _type: 'block',
        children: [
          {
            _key: 'b005c6d03b9c',
            _type: 'span',
            marks: [],
            text: 'Claims crime took place between ',
          },
          {
            _key: '6d816c137f77',
            _type: 'span',
            marks: ['em'],
            text: '10 and 10:10PM',
          },
          {
            _key: '5d616f3235ae',
            _type: 'span',
            marks: [],
            text: ', during his tea time break.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'b7dc06723072',
        _type: 'block',
        children: [
          {
            _key: '7d494ccfc30a',
            _type: 'span',
            marks: [],
            text: 'Said ',
          },
          {
            _key: '257b26db0f50',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '8fdef1e2877e',
            _type: 'span',
            marks: [],
            text: ' was brought to the infirmary by',
          },
          {
            _key: 'dd2cbe681421',
            _type: 'span',
            marks: ['strong'],
            text: ' ',
          },
          {
            _key: 'f8a19c48a502',
            _type: 'span',
            marks: ['em'],
            text: 'Ñenn ',
          },
          {
            _key: '6d8293bbc7c1',
            _type: 'span',
            marks: [],
            text: '& ',
          },
          {
            _key: 'd265c47e4e86',
            _type: 'span',
            marks: ['em'],
            text: 'Sterling',
          },
          {
            _key: 'eb538c672b84',
            _type: 'span',
            marks: [],
            text: ' at',
          },
          {
            _key: 'e92ae7272f87',
            _type: 'span',
            marks: ['em'],
            text: ' 2:12AM.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionC: [
      {
        _key: 'bfa0b599ea82',
        _type: 'block',
        children: [
          {
            _key: 'c07df1f3d8f2',
            _type: 'span',
            marks: ['em'],
            text: 'A “king” who enjoys spying and knowing what time it',
          },
          {
            _key: 'cb0d15a34bdc',
            _type: 'span',
            marks: ['em'],
            text: ' is.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '91854748e82a',
        _type: 'block',
        children: [
          {
            _key: 'd77f0d9c32340',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Innocent',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'e2fd1108f326',
        _type: 'block',
        children: [
          {
            _key: '501ac3bc8dcf',
            _type: 'span',
            marks: [],
            text: 'People watched last night.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'b15888a78f66',
        _type: 'block',
        children: [
          {
            _key: 'cfbc782affd7',
            _type: 'span',
            marks: [],
            text: 'Has video proof that ',
          },
          {
            _key: '6054a6deab11',
            _type: 'span',
            marks: ['em'],
            text: 'Ñenn',
          },
          {
            _key: '925dd0f96af9',
            _type: 'span',
            marks: [],
            text: ' didn’t move last night.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '68398dc62bad',
        _type: 'block',
        children: [
          {
            _key: 'bacc2c35c774',
            _type: 'span',
            marks: [],
            text: 'Saw ',
          },
          {
            _key: '9db6c6c1e405',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '5e72f9edf7e7',
            _type: 'span',
            marks: [],
            text: ' leave his house at ',
          },
          {
            _key: '8976a0808793',
            _type: 'span',
            marks: ['em'],
            text: '9:52PM',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '3b23d27e5211',
        _type: 'block',
        children: [
          {
            _key: '465c1ec35abf',
            _type: 'span',
            marks: [],
            text: 'Claims the crime took place between ',
          },
          {
            _key: 'e4d0b0705104',
            _type: 'span',
            marks: ['em'],
            text: '10 and 10:10PM',
          },
          {
            _key: '71cb3aff5336',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '4cfe02fd2760',
        _type: 'block',
        children: [
          {
            _key: 'a94aeb075238',
            _type: 'span',
            marks: [],
            text: 'Said ',
          },
          {
            _key: '2ea0160889b4',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'a73a3efd515f',
            _type: 'span',
            marks: [],
            text: ' was brought to the infirmary by ',
          },
          {
            _key: '619766846735',
            _type: 'span',
            marks: ['em'],
            text: 'Ñenn',
          },
          {
            _key: 'df0045d2d5da',
            _type: 'span',
            marks: ['em'],
            text: ' ',
          },
          {
            _key: '063cc3fa87f3',
            _type: 'span',
            marks: [],
            text: '& ',
          },
          {
            _key: 'd224a21638d5',
            _type: 'span',
            marks: ['em'],
            text: 'Sterling',
          },
          {
            _key: 'c7dc0d4236c2',
            _type: 'span',
            marks: [],
            text: ' at',
          },
          {
            _key: '59c0ae440973',
            _type: 'span',
            marks: ['em'],
            text: ' 2:12A',
          },
          {
            _key: '08d57f6b6cfd',
            _type: 'span',
            marks: ['em'],
            text: 'M.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionD: [
      {
        _key: '873c48822a66',
        _type: 'block',
        children: [
          {
            _key: 'c8dd11586ff2',
            _type: 'span',
            marks: ['em'],
            text: 'A “king” who enjoys spying and knowing what time it is.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'd9a828b30064',
        _type: 'block',
        children: [
          {
            _key: 'fcd4e28162b1',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Innocent',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
      },
      {
        _key: '420a2709098a',
        _type: 'block',
        children: [
          {
            _key: '317422860ecc',
            _type: 'span',
            marks: [],
            text: 'People watched last night.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '9f92c8e5be5f',
        _type: 'block',
        children: [
          {
            _key: '41117dffbcca',
            _type: 'span',
            marks: [],
            text: 'Has video proof that ',
          },
          {
            _key: '2afb1ba31779',
            _type: 'span',
            marks: ['em'],
            text: 'Ñenn',
          },
          {
            _key: 'b9596a176b4b',
            _type: 'span',
            marks: [],
            text: ' didn’t move last night.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '1f005ce33664',
        _type: 'block',
        children: [
          {
            _key: 'f10093e18ec9',
            _type: 'span',
            marks: [],
            text: 'Saw ',
          },
          {
            _key: '13a1e776072f',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '7c76db79db25',
            _type: 'span',
            marks: [],
            text: ' leave his house at ',
          },
          {
            _key: '11870ecf8340',
            _type: 'span',
            marks: ['em'],
            text: '9:52PM',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'ed5fb94d30ed',
        _type: 'block',
        children: [
          {
            _key: 'bffb5428e0a6',
            _type: 'span',
            marks: [],
            text: 'Claims the crime took place between ',
          },
          {
            _key: '0536e07dcda9',
            _type: 'span',
            marks: ['em'],
            text: '10 and 10:10PM',
          },
          {
            _key: '7bd192762e62',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'b6ac26ca312c',
        _type: 'block',
        children: [
          {
            _key: '63524dc6551b',
            _type: 'span',
            marks: [],
            text: 'Said ',
          },
          {
            _key: '99dd9868a7a2',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'bb2327d43e1e',
            _type: 'span',
            marks: [],
            text: ' was brought to the infirmary by ',
          },
          {
            _key: '123af57c22df',
            _type: 'span',
            marks: ['em'],
            text: 'Ñenn ',
          },
          {
            _key: '0d25d6f09a29',
            _type: 'span',
            marks: [],
            text: '& ',
          },
          {
            _key: 'b56dcced1c23',
            _type: 'span',
            marks: ['em'],
            text: 'Sterling',
          },
          {
            _key: '4cd5965ebc2b',
            _type: 'span',
            marks: [],
            text: ' at',
          },
          {
            _key: '209d9fd5a628',
            _type: 'span',
            marks: ['em'],
            text: ' 2:12AM.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    imageUrl:
      'https://cdn.sanity.io/images/qvonp967/production/ccc47c0c5266c18f970b75f56d3fdb9f5d345846-128x128.png',
    name: 'Elvis',
  },
  {
    descriptionA: [
      {
        _key: 'b36dd9267349',
        _type: 'block',
        children: [
          {
            _key: '569b8e043f390',
            _type: 'span',
            marks: ['em'],
            text: 'The castle guard.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionB: [
      {
        _key: '7a5a28e72935',
        _type: 'block',
        children: [
          {
            _key: '4d055e93f3cd',
            _type: 'span',
            marks: ['em'],
            text: 'The castle guard.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '03d3dcd64da0',
        _type: 'block',
        children: [
          {
            _key: '6fd769392418',
            _type: 'span',
            marks: [],
            text: 'Had a couple of skirmishes with a “shadowy demon” last night. He threw a protein shake at it.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
      },
      {
        _key: 'd5c337a17f45',
        _type: 'block',
        children: [
          {
            _key: 'ba3bb5d959c4',
            _type: 'span',
            marks: [],
            text: 'Is scared of ',
          },
          {
            _key: 'aae64c38537d',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '844a148a8c35',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '63cc815cd2b1',
        _type: 'block',
        children: [
          {
            _key: '431fe84a0aa0',
            _type: 'span',
            marks: ['em'],
            text: 'Ñenn',
          },
          {
            _key: '233dcc32fab6',
            _type: 'span',
            marks: [],
            text: ' got ',
          },
          {
            _key: '097b9cf308cf',
            _type: 'span',
            marks: ['em'],
            text: 'Sterling',
          },
          {
            _key: '9b998d1c646f',
            _type: 'span',
            marks: [],
            text: ' to help them carry ',
          },
          {
            _key: 'a5f95304d5e4',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'da369d1a86c5',
            _type: 'span',
            marks: [],
            text: ' to the infirmary.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'd018a1dc9876',
        _type: 'block',
        children: [
          {
            _key: 'b322110e3db3',
            _type: 'span',
            marks: [],
            text: 'Saw ',
          },
          {
            _key: 'a99a382b5b6e',
            _type: 'span',
            marks: ['em'],
            text: 'Stitches',
          },
          {
            _key: '7808cd394630',
            _type: 'span',
            marks: [],
            text: ' come into the infirmary to give ',
          },
          {
            _key: '6bd051d2b9c2',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'a671eba70713',
            _type: 'span',
            marks: [],
            text: ' stitches.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'db3e2d8f8daf',
        _type: 'block',
        children: [
          {
            _key: '55f875ac1ed2',
            _type: 'span',
            marks: [],
            text: 'Blames the shadowy demon, which he thinks is ',
          },
          {
            _key: '340105091808',
            _type: 'span',
            marks: ['em'],
            text: 'Ñenn',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '5cfb6c17df93',
        _type: 'block',
        children: [
          {
            _key: '478e373d8743',
            _type: 'span',
            marks: [],
            text: 'Really wants me to say “Throw ‘em into the dungeon!”',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '14fb716c08af',
        _type: 'block',
        children: [
          {
            _key: '109a798afab1',
            _type: 'span',
            marks: [],
            text: 'Has a dungeon.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionC: [
      {
        _key: '6bda9b378640',
        _type: 'block',
        children: [
          {
            _key: 'cd62aed1f917',
            _type: 'span',
            marks: [],
            text: 'The castle guard.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'f119225712ef',
        _type: 'block',
        children: [
          {
            _key: '3cf6622bce4b',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Innocent',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'e70ad928bf80',
        _type: 'block',
        children: [
          {
            _key: '2d22fc0087a1',
            _type: 'span',
            marks: [],
            text: 'Had tea time with ',
          },
          {
            _key: '83dc49e412e1',
            _type: 'span',
            marks: ['em'],
            text: 'Elvis',
          },
          {
            _key: 'b821324d7594',
            _type: 'span',
            marks: [],
            text: ' during the window the crime took place.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '85c2535cb91f',
        _type: 'block',
        children: [
          {
            _key: '5bdd73657866',
            _type: 'span',
            marks: [],
            text: 'Had a couple of skirmishes with a “shadowy demon” last night. He threw a protein shake at it.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '345c873d1479',
        _type: 'block',
        children: [
          {
            _key: '116df659bc54',
            _type: 'span',
            marks: [],
            text: 'Helped carry ',
          },
          {
            _key: '3b02fbd3ba96',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '3a9de72c0447',
            _type: 'span',
            marks: [],
            text: ' t',
          },
          {
            _key: 'f76f3ad2c433',
            _type: 'span',
            marks: [],
            text: 'o the infirmary soon after',
          },
          {
            _key: '9712b14885b9',
            _type: 'span',
            marks: ['em'],
            text: ' 2AM',
          },
          {
            _key: '2ccc78bb8a5e',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '972b9b557a37',
        _type: 'block',
        children: [
          {
            _key: '87488eb4a68f',
            _type: 'span',
            marks: [],
            text: 'Really wants me to say “Throw ‘em into the dungeon!”',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '496fb4cdde54',
        _type: 'block',
        children: [
          {
            _key: '3e773fe8b6ad',
            _type: 'span',
            marks: [],
            text: 'Has a dungeon.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionD: [
      {
        _key: 'cd48db0fbcf5',
        _type: 'block',
        children: [
          {
            _key: '0ab25ae969bf',
            _type: 'span',
            marks: [],
            text: 'The castle guard.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'd277d7ba6f37',
        _type: 'block',
        children: [
          {
            _key: '8339b7d1032e',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Innocent',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
      },
      {
        _key: 'a52f406278f6',
        _type: 'block',
        children: [
          {
            _key: '12d73ce1f261',
            _type: 'span',
            marks: [],
            text: 'Had tea time with ',
          },
          {
            _key: '0f6d96017cde',
            _type: 'span',
            marks: ['em'],
            text: 'Elvis',
          },
          {
            _key: '0d0601b2c6ff',
            _type: 'span',
            marks: [],
            text: ' during the window the crime took place.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '528ed9d3db9b',
        _type: 'block',
        children: [
          {
            _key: '797503c7f709',
            _type: 'span',
            marks: [],
            text: 'Had skirmishes with ',
          },
          {
            _key: '03f3d05d3f6f',
            _type: 'span',
            marks: ['em'],
            text: 'Katt',
          },
          {
            _key: '43e77b2dac21',
            _type: 'span',
            marks: [],
            text: ' and ',
          },
          {
            _key: 'c8b4f4159acc',
            _type: 'span',
            marks: ['em'],
            text: 'Ankha',
          },
          {
            _key: 'bc763622f3b2',
            _type: 'span',
            marks: [],
            text: ' last night. He threw a protein shake at ',
          },
          {
            _key: 'f6b2907bcaf8',
            _type: 'span',
            marks: ['em'],
            text: 'Ankha',
          },
          {
            _key: '4d51cb6b5b9c',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '4c88dc9016bf',
        _type: 'block',
        children: [
          {
            _key: '95bc34c205d5',
            _type: 'span',
            marks: [],
            text: 'Helped carry ',
          },
          {
            _key: '554d91f5ec3e',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'fa441756256e',
            _type: 'span',
            marks: [],
            text: ' to the infirmary soon after',
          },
          {
            _key: 'ffce9d0c5d0e',
            _type: 'span',
            marks: ['em'],
            text: ' 2AM',
          },
          {
            _key: '0e22e652f1eb',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'e73df4203068',
        _type: 'block',
        children: [
          {
            _key: 'da649361047c',
            _type: 'span',
            marks: [],
            text: 'Really wants me to say “Throw ‘em into the dungeon!”',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '730dff4525d7',
        _type: 'block',
        children: [
          {
            _key: '616f6a1ecc85',
            _type: 'span',
            marks: [],
            text: 'Has a dungeon.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    imageUrl:
      'https://cdn.sanity.io/images/qvonp967/production/4395ea7500e16861854911d8b533d425fcb877f0-128x128.png',
    name: 'Sterling',
  },
  {
    animalRef: {
      color: {
        _type: 'color',
        alpha: 1,
        hex: '#a76dee',
        hsl: {
          _type: 'hslaColor',
          a: 1,
          h: 267.085693359375,
          l: 0.6809000000000001,
          s: 0.7904000000000004,
        },
        hsv: {
          _type: 'hsvaColor',
          a: 1,
          h: 267.085693359375,
          s: 0.5405897380631859,
          v: 0.9331166400000002,
        },
        rgb: {
          _type: 'rgbaColor',
          a: 1,
          b: 238,
          g: 109,
          r: 167,
        },
      },
    },
    descriptionA: [
      {
        _key: '18f113ee5a05',
        _type: 'block',
        children: [
          {
            _key: '3802ecae7a6d0',
            _type: 'span',
            marks: ['em'],
            text: 'My client who is accused of almost murdering the victim.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'd30a0677daf6',
        _type: 'block',
        children: [
          {
            _key: '1ebb123884be',
            _type: 'span',
            marks: [],
            text: 'Was wishing on stars the whole night.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'c87ce47d777e',
        _type: 'block',
        children: [
          {
            _key: '24078ac6a9500',
            _type: 'span',
            marks: [],
            text: 'Found the victim, ',
          },
          {
            _key: '2537c5cdae47',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'e13a5138296d',
            _type: 'span',
            marks: [],
            text: ', at ',
          },
          {
            _key: 'ade0ebf61006',
            _type: 'span',
            marks: ['em'],
            text: '2AM ish',
          },
          {
            _key: '54b0bd81fe9d',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '8e9eed39b645',
        _type: 'block',
        children: [
          {
            _key: '9426dda880d00',
            _type: 'span',
            marks: [],
            text: 'Got ',
          },
          {
            _key: 'dd26dae58ac0',
            _type: 'span',
            marks: ['em'],
            text: 'Sterling',
          },
          {
            _key: '871591c3710a',
            _type: 'span',
            marks: [],
            text: ' to help carry ',
          },
          {
            _key: '768f23922b93',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'a732a116e28c',
            _type: 'span',
            marks: [],
            text: ' to the infirmary.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '7c3918d5a0c1',
        _type: 'block',
        children: [
          {
            _key: '877d3e9789fa0',
            _type: 'span',
            marks: [],
            text: 'Followed ',
          },
          {
            _key: '7425cd24986e',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'c434cc91887c',
            _type: 'span',
            marks: ['em'],
            text: '’s',
          },
          {
            _key: 'eb32bd71115d',
            _type: 'span',
            marks: [],
            text: ' request to retrieve ',
          },
          {
            _key: '6e9a30c4a80b',
            _type: 'span',
            marks: ['em'],
            text: 'Stitches',
          },
          {
            _key: '9c471849705b',
            _type: 'span',
            marks: [],
            text: ' so ',
          },
          {
            _key: 'f5419f4a79eb',
            _type: 'span',
            marks: ['em'],
            text: 'Stitches',
          },
          {
            _key: 'ac3232e12fa0',
            _type: 'span',
            marks: [],
            text: ' could give ',
          },
          {
            _key: '6bfaaf6ea3c1',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'c46f27df7a92',
            _type: 'span',
            marks: [],
            text: ' stitches.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '33fcb6cfa6f2',
        _type: 'block',
        children: [
          {
            _key: 'be8221dc2c7b0',
            _type: 'span',
            marks: [],
            text: 'Is considered suspicious by the others because they found the body and they’re kinda weird.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '47d36c80f567',
        _type: 'block',
        children: [
          {
            _key: '7a5e7f0ba4fe',
            _type: 'span',
            marks: [],
            text: 'Doesn’t know what happened but is convinced it wasn’t an accident.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '2462149558a7',
        _type: 'block',
        children: [
          {
            _key: '5f1d52ecdce8',
            _type: 'span',
            marks: [],
            text: 'They gave me a snazzy bag.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionB: [
      {
        _key: '1ab8dbe63b39',
        _type: 'block',
        children: [
          {
            _key: 'c59019c7861e',
            _type: 'span',
            marks: ['em'],
            text: 'My client who is accused of almost murdering the victim.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '3f83caf7b61c',
        _type: 'block',
        children: [
          {
            _key: 'aa7074341031',
            _type: 'span',
            marks: [],
            text: 'Was wishing on stars the whole night.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '63fa482b542a',
        _type: 'block',
        children: [
          {
            _key: '7e10ea24e3f1',
            _type: 'span',
            marks: [],
            text: 'Found the victim, ',
          },
          {
            _key: '9ed624c00700',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '92c00d83a78b',
            _type: 'span',
            marks: [],
            text: ', at ',
          },
          {
            _key: 'f54d75a2eafe',
            _type: 'span',
            marks: ['em'],
            text: '2AM ish',
          },
          {
            _key: 'be2cee1986bb',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '602d22b85797',
        _type: 'block',
        children: [
          {
            _key: '350d3be09a01',
            _type: 'span',
            marks: [],
            text: 'Got ',
          },
          {
            _key: 'ee849f1e81b7',
            _type: 'span',
            marks: ['em'],
            text: 'Sterling',
          },
          {
            _key: '43e1c5099e71',
            _type: 'span',
            marks: [],
            text: ' to help carry ',
          },
          {
            _key: 'ffd3ebc2f045',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'b4aa1d723a9e',
            _type: 'span',
            marks: [],
            text: ' to the infirmary.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '0fbeba970bd8',
        _type: 'block',
        children: [
          {
            _key: 'df8a53d5b0c0',
            _type: 'span',
            marks: [],
            text: 'Followed ',
          },
          {
            _key: 'b1416aae9135',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky’s',
          },
          {
            _key: 'ac4520854ca9',
            _type: 'span',
            marks: [],
            text: ' request to retrieve ',
          },
          {
            _key: '872a7309a4bc',
            _type: 'span',
            marks: ['em'],
            text: 'Stitches',
          },
          {
            _key: '746d49659397',
            _type: 'span',
            marks: [],
            text: ' so ',
          },
          {
            _key: 'cc4f2e90094f',
            _type: 'span',
            marks: ['em'],
            text: 'Stitches',
          },
          {
            _key: '1f24d8f07c42',
            _type: 'span',
            marks: [],
            text: ' could give ',
          },
          {
            _key: '434d77d6a107',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'bc7268bf85a2',
            _type: 'span',
            marks: [],
            text: ' stitches.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '7cf2c669a4ed',
        _type: 'block',
        children: [
          {
            _key: 'fca340f84f23',
            _type: 'span',
            marks: [],
            text: 'Is considered suspicious by the others because they found the body and they’re kinda weird.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '51fd6995465c',
        _type: 'block',
        children: [
          {
            _key: 'ece9867d2cb5',
            _type: 'span',
            marks: [],
            text: 'Doesn’t know what happened but is convinced it wasn’t an accident.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'f689db3645b3',
        _type: 'block',
        children: [
          {
            _key: 'a2a62db2e50c',
            _type: 'span',
            marks: [],
            text: 'They gave me a snazzy bag.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionC: [
      {
        _key: 'bb5f474bc0b0',
        _type: 'block',
        children: [
          {
            _key: '70bb499b9ca50',
            _type: 'span',
            marks: ['em'],
            text: 'My client, whose name I successfully cleared.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'e24f1d3a152a',
        _type: 'block',
        children: [
          {
            _key: '0b9d3d0e062e0',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Innocent',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '13c0d80244b6',
        _type: 'block',
        children: [
          {
            _key: 'ae7f3a99ea44',
            _type: 'span',
            marks: [],
            text: 'Was wishing on stars the whole night. There’s video proof.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '5e690c602ff3',
        _type: 'block',
        children: [
          {
            _key: '6fbad9db1b5f',
            _type: 'span',
            marks: [],
            text: 'Found the victim, ',
          },
          {
            _key: '82df2a1d4b14',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '163c37579a2b',
            _type: 'span',
            marks: [],
            text: ', at ',
          },
          {
            _key: 'fd2aae49deaf',
            _type: 'span',
            marks: ['em'],
            text: '2AM',
          },
          {
            _key: 'cf6140389df0',
            _type: 'span',
            marks: [],
            text: ' ',
          },
          {
            _key: '92c2471c2fa2',
            _type: 'span',
            marks: ['em'],
            text: 'ish',
          },
          {
            _key: 'fbdf519db10d',
            _type: 'span',
            marks: [],
            text: ', and took care of him with the help of ',
          },
          {
            _key: '525bbb371472',
            _type: 'span',
            marks: ['em'],
            text: 'Sterling ',
          },
          {
            _key: '0c0be28eca10',
            _type: 'span',
            marks: [],
            text: '&',
          },
          {
            _key: 'fcefa731408a',
            _type: 'span',
            marks: ['em'],
            text: ' Stitches',
          },
          {
            _key: '01877fc5393c',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionD: [
      {
        _key: '9c4ff1f07936',
        _type: 'block',
        children: [
          {
            _key: '82ae68983538',
            _type: 'span',
            marks: ['em'],
            text: 'My client who logged off.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '224c38292bac',
        _type: 'block',
        children: [
          {
            _key: '484edd16b038',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Innocent',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
      },
      {
        _key: '6ceb36a5cdce',
        _type: 'block',
        children: [
          {
            _key: '9fe5736aa834',
            _type: 'span',
            marks: [],
            text: 'Was wishing on stars the whole night. There’s video proof.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'e970123dc4e0',
        _type: 'block',
        children: [
          {
            _key: '25cef610a1e1',
            _type: 'span',
            marks: [],
            text: 'Found the victim, ',
          },
          {
            _key: '92e70d64a27a',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '2123a59d56f1',
            _type: 'span',
            marks: [],
            text: ', at ',
          },
          {
            _key: 'f90593b8d16d',
            _type: 'span',
            marks: ['em'],
            text: '2AM',
          },
          {
            _key: 'b5dbbf34da78',
            _type: 'span',
            marks: [],
            text: ' ',
          },
          {
            _key: 'b99d45bf085d',
            _type: 'span',
            marks: ['em'],
            text: 'ish',
          },
          {
            _key: '58c040e8b9e1',
            _type: 'span',
            marks: [],
            text: ', and took care of him with the help of ',
          },
          {
            _key: '941c64464036',
            _type: 'span',
            marks: ['em'],
            text: 'Sterling ',
          },
          {
            _key: '2455fcb74ea2',
            _type: 'span',
            marks: [],
            text: '&',
          },
          {
            _key: 'cca66a409684',
            _type: 'span',
            marks: ['em'],
            text: ' Stitches',
          },
          {
            _key: 'e70857ec46d5',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    imageUrl:
      'https://cdn.sanity.io/images/qvonp967/production/a584821da98bc184118e58225c025ddb8d3fbcc9-216x216.png',
    name: 'Ñenn',
    nickname: ['representative', 'Representative'],
  },
  {
    descriptionA: [
      {
        _key: 'cdf571225ca2',
        _type: 'block',
        children: [
          {
            _key: '4e2c43597af4',
            _type: 'span',
            marks: ['em'],
            text: 'The squirrel tha',
          },
          {
            _key: 'd67dfbf45ac8',
            _type: 'span',
            marks: ['em'],
            text: 't is primarily accusing my client.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionB: [
      {
        _key: 'ad82c94d7275',
        _type: 'block',
        children: [
          {
            _key: '4367e6d0a28c',
            _type: 'span',
            marks: ['em'],
            text: 'My partner(?) who is trying to imprison my client.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '459fc57fcfd2',
        _type: 'block',
        children: [
          {
            _key: '77513026eaa4',
            _type: 'span',
            marks: [],
            text: 'Spent the night with ',
          },
          {
            _key: '3601fcc04e1f',
            _type: 'span',
            marks: ['em'],
            text: 'Chadder ',
          },
          {
            _key: '126e18649aab',
            _type: 'span',
            marks: [],
            text: '& ',
          },
          {
            _key: '7334559f8315',
            _type: 'span',
            marks: ['em'],
            text: 'Merengue',
          },
          {
            _key: '07a7de347d16',
            _type: 'span',
            marks: [],
            text: ' at their place.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'fdaacc7af259',
        _type: 'block',
        children: [
          {
            _key: '8a648a1a2016',
            _type: 'span',
            marks: [],
            text: 'Was “totes conscious the whole time.”',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'cfe6081f93a3',
        _type: 'block',
        children: [
          {
            _key: '7d46be46dd81',
            _type: 'span',
            marks: [],
            text: 'Convinced ',
          },
          {
            _key: '37c62b494e37',
            _type: 'span',
            marks: ['em'],
            text: 'Ñenn',
          },
          {
            _key: 'a8cea089135e',
            _type: 'span',
            marks: [],
            text: ' did it.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionC: [
      {
        _key: 'f0e75a6af5c0',
        _type: 'block',
        children: [
          {
            _key: 'ec453cf083510',
            _type: 'span',
            marks: ['em'],
            text: 'My partner who is now on the same page as me.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'ed146dfab70b',
        _type: 'block',
        children: [
          {
            _key: '4e59d65aebdf0',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Innocent',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'e5abca5152cc',
        _type: 'block',
        children: [
          {
            _key: '801ea64bb83c',
            _type: 'span',
            marks: [],
            text: 'Spent last night unconscious at ',
          },
          {
            _key: '6159ef953648',
            _type: 'span',
            marks: ['em'],
            text: 'Chadder’s',
          },
          {
            _key: '83b3216dd9b2',
            _type: 'span',
            marks: [],
            text: ' & ',
          },
          {
            _key: 'f03304be1439',
            _type: 'span',
            marks: ['em'],
            text: 'Merengue’s',
          },
          {
            _key: '34023eefe824',
            _type: 'span',
            marks: [],
            text: ' place.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionD: [
      {
        _key: '47eb0b3f8aa2',
        _type: 'block',
        children: [
          {
            _key: '544698ef4eb6',
            _type: 'span',
            marks: ['em'],
            text: 'My partner who I relatively trust now.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '20debd53bbc3',
        _type: 'block',
        children: [
          {
            _key: '0e6ce8940c7e',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Innocent',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
      },
      {
        _key: 'b3ec257407a4',
        _type: 'block',
        children: [
          {
            _key: 'fb82c3a731e8',
            _type: 'span',
            marks: [],
            text: 'Spent last night unconscious at ',
          },
          {
            _key: 'de94b60c38bf',
            _type: 'span',
            marks: ['em'],
            text: 'Chadder’s',
          },
          {
            _key: 'b5deef535506',
            _type: 'span',
            marks: [],
            text: ' & ',
          },
          {
            _key: '6f858e27cd1f',
            _type: 'span',
            marks: ['em'],
            text: 'Merengue’s',
          },
          {
            _key: '7121022aa6a7',
            _type: 'span',
            marks: [],
            text: ' place.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    imageUrl:
      'https://cdn.sanity.io/images/qvonp967/production/c803c1251600e1762a9a7c129a6834a3f86adf73-128x128.png',
    name: 'Agent S',
  },
  {
    descriptionA: [
      {
        _key: '547787741587',
        _type: 'block',
        children: [
          {
            _key: '46b69b2345160',
            _type: 'span',
            marks: ['em'],
            text: 'A cat that has a lot of stuff.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionB: [
      {
        _key: '4bb7763c8dc8',
        _type: 'block',
        children: [
          {
            _key: 'c05d3337195e',
            _type: 'span',
            marks: ['em'],
            text: 'The cat that went on about how much they hate the victim.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '3c93a12f4cc4',
        _type: 'block',
        children: [
          {
            _key: '3c1dba6e7e45',
            _type: 'span',
            marks: [],
            text: 'Was on a stroll last night, back home by 11PM. Hadn’t left since.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '261ba2a7a7de',
        _type: 'block',
        children: [
          {
            _key: 'c874fd7c70e8',
            _type: 'span',
            marks: [],
            text: 'Mad at ',
          },
          {
            _key: '1fe6ef1df3a5',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '20046a622aec',
            _type: 'span',
            marks: [],
            text: ' for breaking her bunny-day wardrobe',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '78d7912ad4c2',
        _type: 'block',
        children: [
          {
            _key: '00fa9febe348',
            _type: 'span',
            marks: [],
            text: 'Thinks ',
          },
          {
            _key: 'ac32df1b9f4e',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'aae2a532ef41',
            _type: 'span',
            marks: [],
            text: ' accidentally hit his head on a money rock.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionC: [
      {
        _key: '8aa6de9dd804',
        _type: 'block',
        children: [
          {
            _key: '9080560617f5',
            _type: 'span',
            marks: ['em'],
            text: 'The cat that went on about how much they hate the victim.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'a36af7e010a6',
        _type: 'block',
        children: [
          {
            _key: '745385e56157',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Suspect',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '61ae81fd6130',
        _type: 'block',
        children: [
          {
            _key: 'f757fe9b5665',
            _type: 'span',
            marks: [],
            text: 'Claimed to be on a stroll last night, back home by ',
          },
          {
            _key: '77c9eb70a71e',
            _type: 'span',
            marks: ['em'],
            text: '11PM',
          },
          {
            _key: '5f5502a52fdc',
            _type: 'span',
            marks: [],
            text: '. Hadn’t left since.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '6d1481aed3f1',
        _type: 'block',
        children: [
          {
            _key: 'f5e347aefcbb',
            _type: 'span',
            marks: [],
            text: 'Mad at',
          },
          {
            _key: 'd800886edbe6',
            _type: 'span',
            marks: [],
            text: ' ',
          },
          {
            _key: 'cbc234e358c3',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '27d314dbb0fc',
            _type: 'span',
            marks: [],
            text: ' fo',
          },
          {
            _key: '1e2cf25f0f49',
            _type: 'span',
            marks: [],
            text: 'r breaking her bunny-day wardrobe',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '2cda8824b4d7',
        _type: 'block',
        children: [
          {
            _key: 'b9483cf52103',
            _type: 'span',
            marks: [],
            text: 'Had the money rock theory.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    descriptionD: [
      {
        _key: 'fafb78bb3f57',
        _type: 'block',
        children: [
          {
            _key: '05e280b9011e',
            _type: 'span',
            marks: ['em'],
            text: 'The cat that went on about how much they hate the victim.',
          },
        ],
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'ce1659cc5d2e',
        _type: 'block',
        children: [
          {
            _key: '611cec07517c',
            _type: 'span',
            marks: ['strong', 'em'],
            text: 'Suspect',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'ae8c7ff5b69c',
        _type: 'block',
        children: [
          {
            _key: 'c5059f4937610',
            _type: 'span',
            marks: [],
            text: 'Was out stealing last night.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: 'a13a14f75c2c',
        _type: 'block',
        children: [
          {
            _key: '50b2db504f36',
            _type: 'span',
            marks: [],
            text: 'Stole from ',
          },
          {
            _key: '487c22cab962',
            _type: 'span',
            marks: ['em'],
            text: 'Merengue',
          },
          {
            _key: '06776c2e9740',
            _type: 'span',
            marks: [],
            text: ', ',
          },
          {
            _key: '740ab76c3401',
            _type: 'span',
            marks: ['em'],
            text: 'Sterling',
          },
          {
            _key: '9cea9bf5b99e',
            _type: 'span',
            marks: [],
            text: ', and ',
          },
          {
            _key: '0048a2f8a625',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: 'beb9319d37a4',
            _type: 'span',
            marks: [],
            text: '.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '32d79216a62c',
        _type: 'block',
        children: [
          {
            _key: '25708895ab70',
            _type: 'span',
            marks: [],
            text: 'Has a history of being cruel to the victim.',
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
      {
        _key: '36dc07f69683',
        _type: 'block',
        children: [
          {
            _key: 'a7699ae0fd55',
            _type: 'span',
            marks: [],
            text: 'Saw ',
          },
          {
            _key: 'e7d1365098f7',
            _type: 'span',
            marks: ['em'],
            text: 'Lucky',
          },
          {
            _key: '6a3014706201',
            _type: 'span',
            marks: [],
            text: ' unc',
          },
          {
            _key: 'b5a08c3fd9a6',
            _type: 'span',
            marks: [],
            text: "onscious and didn't help. Instead, she used it as an opportunity to steal from the victim.",
          },
        ],
        level: 1,
        listItem: 'bullet',
        markDefs: [],
        style: 'normal',
      },
    ],
    imageUrl:
      'https://cdn.sanity.io/images/qvonp967/production/ca7d7d2dc62f5913889d8a1724074c1cb174fa2f-128x128.png',
    name: 'Ankha',
  },
];

export default notes;
